name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
      - run: shards install
      - run: crystal tool format --check
      - run: ./bin/ameba

  Specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crystal: [1.1.1, 1.2.2, latest, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - run: shards install
      - run: crystal spec
